nvidia-select : finish with a few suggestions

diff --git a/components/openindiana/nvidia-select/files/nvidia-select b/components/openindiana/nvidia-select/files/nvidia-select
--- a/components/openindiana/nvidia-select/files/nvidia-select
+++ b/components/openindiana/nvidia-select/files/nvidia-select
@@ -385,6 +385,12 @@ if [ "$BASEDIR" = / ]; then
     load_drv /kernel/misc/gfx_private
     load_drv /kernel/drv/nvidia
     load_drv /kernel/drv/nvidia_modeset
+
+    echo "NOTE: if (re)loading of drivers failed, you may have to reboot ..." >&2
 fi
+
+echo "NOTE: Consider also configuring ogl-select for nvidia:" >&2
+echo "  svccfg -s ogl-select setprop options/vendor = nvidia" >&2
+echo "  svcadm restart ogl-select" >&2
 
 exit 0
