nvidia-select : rearrange reloading a kernel module, and try to reload all involved (nvidia, nvidia_modeset, gfx_private)

diff --git a/components/openindiana/nvidia-select/files/nvidia-select b/components/openindiana/nvidia-select/files/nvidia-select
--- a/components/openindiana/nvidia-select/files/nvidia-select
+++ b/components/openindiana/nvidia-select/files/nvidia-select
@@ -183,6 +183,66 @@ check_add_drv()
     fi
 }
 
+unload_drv() {
+    DRV_PATH="$1"
+    DRV="`basename "$DRV_PATH"`"
+
+    echo "INFO: Trying to unload the kernel driver $DRV..." 2>&1
+    OLD_DRV="`/usr/sbin/modinfo | awk '( $6 == "'"$DRV"'") { print $0 }'`" \
+    || OLD_DRV=""
+    eval OLD_DRV_${DRV}=\""$OLD_DRV"\"
+
+    if [ -n "$OLD_DRV" ] ; then
+        echo "INFO: Old driver info:" >&2
+        echo "$OLD_DRV" >&2
+        /usr/sbin/modunload -i `echo "$OLD_DRV" | head -1 | awk '{print $1}'` \
+            || { echo "FAILED to unload the old kernel driver $DRV..." ; return 1; }
+    fi
+}
+
+load_drv() {
+    # NOTE: Uses OLD_DRV data set by unload_drv above
+    DRV_PATH="$1"
+    DRV="`basename "$DRV_PATH"`"
+
+    echo "INFO: Trying to (re)load the kernel driver $DRV..." 2>&1
+    [ -s "$DRV_PATH" ] || { echo "SKIP: No such file: $DRV_PATH" >&2; return 1; }
+
+    case "`isainfo`" in
+        *amd64*)
+            modload "`dirname "$DRV_PATH"`/amd64/$DRV" ;;
+        *sparcv9*)
+            modload "`dirname "$DRV_PATH"`/sparcv9/$DRV" ;;
+        *i386*|*sparcv7*)
+            modload "$DRV_PATH" ;;
+        *)  echo "Unexpected architecture: `isainfo`" >&2
+            return 2
+            ;;
+    esac
+    [ $? = 0 ] || echo "FAILED to load the new kernel driver $DRV..."
+
+    NEW_DRV="`/usr/sbin/modinfo | awk '( $6 == "'"$DRV"'") { print $0 }'`" \
+    || NEW_DRV=""
+    eval NEW_DRV_${DRV}=\""$NEW_DRV"\"
+    eval OLD_DRV=\""\$OLD_DRV_${DRV}"\"
+
+    if [ -n "$NEW_DRV" ] ; then
+        if [ "$NEW_DRV" = "$OLD_DRV" ] ; then
+            echo "INFO: New $DRV driver seems to be same as the old one" >&2
+        else
+            echo "INFO: New $DRV driver info:" >&2
+            echo "$NEW_DRV" >&2
+        fi
+    else
+        echo "FAILED to find any details about the newly loaded driver $DRV" >&2
+    fi
+}
+
+reload_drv() {
+    unload_drv "$@"
+    load_drv "$@"
+}
+
 
 if [ -z "${BASEDIR-}" ]; then
     BASEDIR="/"
@@ -264,8 +324,16 @@ if [ -z "$NVIDIA_VERSION" ] \
         "got '$NVIDIA_VERSION'"
 fi
 
+if [ "$BASEDIR" = / ]; then
+    echo "INFO: unloading old drivers ..." >&2
+    unload_drv /kernel/drv/nvidia_modeset
+    unload_drv /kernel/drv/nvidia
+    unload_drv /kernel/misc/gfx_private
+fi
+
 echo "INFO: uninstalling driver associations under $BASEDIR ..." >&2
 uninstall
+[ "$USER_ACTION" = uninstall ] && exit 0
 
 ALTROOT_FLAG=""
 [ "$BASEDIR" = "/" ] || ALTROOT_FLAG="chroot '$BASEDIR'"
@@ -310,37 +378,13 @@ if [ -n "$SMF_ACTION" ] || [ "$BASEDIR" = / -a "$UPDATE_SMF" = "yes" ] ; then
         || die "Failed to remember NVIDIA_VERSION='$NVIDIA_VERSION' into SMF properties for '$SMF_FMRI'"
 fi
 
-# TOTHINK: Should any failures here be fatal? e.g. mismatch of drv vs. hw?..
-echo "INFO: Trying to (re)load the kernel driver..." 2>&1
-OLD_DRV="`/usr/sbin/modinfo | awk '( $6 == "nvidia") { print $0 }`" || OLD_DRV=""
-if [ -n "$OLD_DRV" ] ; then
-    echo "INFO: Old driver info:" >&2
-    echo "$OLD_DRV" >&2
-    /usr/sbin/modunload -i `echo "$OLD_DRV" | head -1 | awk '{print $1}'` \
-        || echo "FAILED to unload the old kernel driver..."
+# TOTHINK: Should any failures here be fatal?
+# e.g. mismatch of drv vs. hw?..
+if [ "$BASEDIR" = / ]; then
+    echo "INFO: loading new drivers ..." >&2
+    load_drv /kernel/misc/gfx_private
+    load_drv /kernel/drv/nvidia
+    load_drv /kernel/drv/nvidia_modeset
 fi
 
-case "`isainfo`" in
-    *amd64*)
-        modload /kernel/drv/amd64/nvidia ;;
-    *sparcv9*)
-        modload /kernel/drv/sparcv9/nvidia ;;
-    *i386*|*sparcv7*)
-        modload /kernel/drv/nvidia ;;
-    *)  echo "Unexpected architecture: `isainfo`" >&2
-        exit 0
-        ;;
-esac
-[ $? = 0 ] || echo "FAILED to load the new kernel driver..."
-
-NEW_DRV="`/usr/sbin/modinfo | awk '( $6 == "nvidia") { print $0 }`" || NEW_DRV=""
-if [ -n "$NEW_DRV" ] ; then
-    if [ "$NEW_DRV" = "$OLD_DRV" ] ; then
-        echo "INFO: New driver seems to be same as the old one" >&2
-    else
-        echo "INFO: New driver info:" >&2
-        echo "$NEW_DRV" >&2
-    fi
-else
-    echo "FAILED to find any details about the newly loaded driver" >&2
-fi
+exit 0
