6926434 ib_read_bw, ib_read_lat: OFED utilities sometimes hang when using "-e" (event) flag 6996726 "rds-stress --show-perfdata" option is broken. 7003185 rds-stress man page needs cleanup 7005654 qperf: 32bit only: qperf fails in all RC/UD streaming tests 7024095 set_nodedesc.sh: heading whitespace of HCA specific desc string is ignored if '-N' not specified 7043392 OFED 1.5.3: test_verbs: 'resize CQ' test failed on tavor 7043758 OFED 1.5.3: test_verbs: core dump while during async test on tavor with snv_166 7044543 ibsysstat server process fails to get cpu info 7046730 ibstatus needs to clean up after itself 7050802 OFED 1.5.3: ib_send_bw/ib_send_lat doesn't work with '-g' option 7061241 OFED 1.5.3 ib_read_lat/ib_read_bw don't work between tavor and hermon 7087339 modify solaris changes to libmlx4 to use returned inline size from hermon driver 7090343 solaris_set_nodedesc: the -N option does not work 7091277 /usr/man/man3/ibnd_debug.3 and ibnd_destroy_fabric.3 refer to non-existence ibnd_discover_fabric.3 7091649 OFED 1.5.3: ibdiagnet: "-vlr -r" shows file open failure messages on Solaris 7093499 ib_rdma_lat, ib_read_lat, ib_write_lat and other IB verb latency tools should use gethrtime 7095000 mem leak in libibvers ibv_read_sysfs_file() 7095879 resize cq in libmlx4 incorrect 7095943 rdma_lat & rdma_bw core dump on non ib system 7099692 Add man pages for OFUV perftest utilities 7108873 definitions in sol_uverbs_ioctl.h & sol_umad_ioctl.h are duplicated in solaris_compatibility.c 7119924 ibportstate: operations enable, disable, and reset should only be allowed on switch ports 7120891 ibv_devinfo should report a valid active_mtu instead of 'Unknown' 7141996 sol_uverbs should provide ioctl calls to get GIDs and PKEYs for libibverbs (userland changes) 7144445 setnodedesc.sh -v white space issue 7146479 qperf --cpu_affinity doesn't match with solaris cpu no. 7146482 qperf -cm1 sometimes failed with "rdma_listen failed" message

diff --git a/components/open-fabrics/infiniband-diags/patches/base.patch b/components/open-fabrics/infiniband-diags/patches/base.patch
--- a/components/open-fabrics/infiniband-diags/patches/base.patch
+++ b/components/open-fabrics/infiniband-diags/patches/base.patch
@@ -259,7 +259,7 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/set_nodedesc.sh infiniband-diags-
 +# Call solaris_set_nodedesc, if operating system is SunOS
 +os=`uname -s`
 +if [ $os == "SunOS" ]; then
-+	solaris_set_nodedesc $*
++	solaris_set_nodedesc "$@"
 +	rc=$?
 +	exit $rc
 +fi
@@ -436,12 +436,12 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibstatus infiniband-diags-1.5.8/s
 -infiniband_base="/sys/class/infiniband"
 -def_ibdev="mthca0"
 +ibvdevinfo="/usr/bin/ibv_devinfo"
-+ibvdevinfo_results="/tmp/ibvdevinfo.output"
-+tmpout="/tmp/tmpout"
++ibvdevinfo_results="/tmp/ibvdevinfo.output.$$"
++tmpout="/tmp/tmpout.$$"
  
  usage() {
  	prog=`basename $0`
-@@ -10,58 +11,119 @@
+@@ -10,58 +11,128 @@
  	echo "Usage: " $prog " [-h] [devname[:portnum]]"
  	echo "	-h:	this help screen"
  	echo "	Examples:"
@@ -528,10 +528,14 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibstatus infiniband-diags-1.5.8/s
 +		}
 +	}
 +	END {
-+		if (hcaid_in != "+" && port_in == "+" && hcaid_hit == 0)
++		if (hcaid_in != "+" && port_in == "+" && hcaid_hit == 0) {
 + 			printf("Fatal error: device '\''%s'\'' not found\n\n", hcaid_in)
-+		if (hacid_in != "+" && port_in != "+" && port_hit == 0)
++			exit 1;
++		}
++		if (hacid_in != "+" && port_in != "+" && port_hit == 0) {
 + 			printf("Fatal error: port '\''%s:%d'\'' not found\n\n", hcaid_in, port_in)
++			exit 1;
++		}
 +	}' $tmpout
  }
  
@@ -554,24 +558,23 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibstatus infiniband-diags-1.5.8/s
 +# Check to see if /usr/bin/ibv_devinfo exists.
 +if [ ! -x $ibvdevinfo ]; then
 +	echo "$ibvdevinfo doesn't exist!"
-+	exit 0
++	exit 1
 +fi
  
 -ib_status() {
 -	ports_dir="$infiniband_base/$1/ports"
-+rm -rf $ibvdevinfo_results
- 
--	if ! [ -d "$ports_dir" ]; then
--		fatal "device '$1': sys files not found ($ports_dir)"
--	fi
 +# Run ibv_devinfo and direct the output to $ibvdevinfo_results.
 +$ibvdevinfo -v > $ibvdevinfo_results
 +if [ $? != 0 ]; then
 +	echo "$ibvdevinfo failed!"
-+	exit 0
++	exit 1
 +fi
 +#
  
+-	if ! [ -d "$ports_dir" ]; then
+-		fatal "device '$1': sys files not found ($ports_dir)"
+-	fi
+-
 -	if [ "$2" = "+" ]; then
 -		ports=`(cd "$infiniband_base/$1/ports" 2>/dev/null || fatal No devices; echo *)`
 -	else
@@ -588,10 +591,12 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibstatus infiniband-diags-1.5.8/s
 +nhcas=`$ibvdevinfo -l | awk '/HCA/{print $1}'`
 +if [ -z $nhcas ]; then
 +        echo "No HCAs!"
-+	exit 0
++	rm -f $ibvdevinfo_results
++	exit 1
  fi
  
 +egrep "port:|hca_id:|_lid|GID|state:|active_|link_layer:" $ibvdevinfo_results |grep -v _mtu | sed -e 's/(//' -e 's/)//' > $tmpout
++rm -f $ibvdevinfo_results
 +
  if [ -z "$1" ]; then
 -	cd $infiniband_base 2>/dev/null || fatal No devices
@@ -599,18 +604,28 @@ diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibstatus infiniband-diags-1.5.8/s
 -		ib_status $dev "+";
 -	done
 +	get_status_ports "+" "+"
++	if [ $? != 0 ]; then
++		rm -f $tmpout
++		exit 1
++	fi
++	rm -f $tmpout
  	exit 0
  fi
  
-@@ -73,6 +135,7 @@
+@@ -73,6 +144,12 @@
  		port="+"
  	fi
  
 -	ib_status $dev $port
 +	get_status_ports $dev $port
++	if [ $? != 0 ]; then
++		rm -f $tmpout
++		exit 1
++	fi
 +
  	shift
  done
++rm -f $tmpout
 diff -r -u /tmp/infiniband-diags-1.5.8/scripts/ibcheckwidth.in infiniband-diags-1.5.8/scripts/ibcheckwidth.in
 --- /tmp/infiniband-diags-1.5.8/scripts/ibcheckwidth.in	Wed Feb 16 02:13:21 2011
 +++ infiniband-diags-1.5.8/scripts/ibcheckwidth.in	Thu Feb 24 11:26:54 2011
@@ -1577,6 +1592,133 @@ diff -r -u /tmp/infiniband-diags-1.5.8/infiniband-diags.spec.in infiniband-diags
  %{_mandir}/man3/*
  %doc README COPYING ChangeLog
  
+diff -r -u /tmp/infiniband-diags-1.5.8/src/ibsysstat.c infiniband-diags-1.5.8/src/ibsysstat.c
+--- /tmp/infiniband-diags-1.5.8/src/ibsysstat.c	Wed Feb 16 02:13:21 2011
++++ infiniband-diags-1.5.8/src/ibsysstat.c	Wed Oct  5 09:27:26 2011
+@@ -40,6 +40,7 @@
+ #include <unistd.h>
+ #include <string.h>
+ #include <getopt.h>
++#include <signal.h>
+ 
+ #include <infiniband/umad.h>
+ #include <infiniband/mad.h>
+@@ -62,7 +63,7 @@
+ } cpu_info;
+ 
+ static cpu_info cpus[MAX_CPUS];
+-static int host_ncpu;
++static int host_ncpu = 0;
+ 
+ static int server_respond(void *umad, int size)
+ {
+@@ -142,7 +143,8 @@
+ 		break;
+ 	case IB_CPUINFO_ATTR:
+ 		s[0] = '\0';
+-		for (i = 0; i < host_ncpu && sz > 0; i++) {
++		for (i = 0; i < host_ncpu && sz > 0 && ret < 
++		    IB_VENDOR_RANGE2_DATA_SIZE; i++) {
+ 			n = snprintf(s, sz, "cpu %d: model %s MHZ %s\n",
+ 				     i, cpus[i].model, cpus[i].mhz);
+ 			if (n >= sz) {
+@@ -154,6 +156,8 @@
+ 			s += n;
+ 			ret += n;
+ 		}
++		if (i < host_ncpu)
++			IBWARN("cpuinfo truncated");
+ 		ret++;
+ 		break;
+ 	default:
+@@ -162,6 +166,20 @@
+ 	return ret;
+ }
+ 
++void cleanup(int sig)
++{
++	int	i;
++	for (i = 0; i < host_ncpu ; i++) {
++		if (cpus[i].model)
++			free(cpus[i].model);
++		if (cpus[i].mhz)
++			free(cpus[i].mhz);
++	}
++	mad_rpc_close_port(srcport);
++	(void) signal(SIGINT, SIG_DFL);
++	exit (0);
++}
++
+ static uint8_t buf[2048];
+ 
+ static char *ibsystat_serv(void)
+@@ -171,6 +189,7 @@
+ 	int attr, mod, size;
+ 
+ 	DEBUG("starting to serve...");
++	(void) signal(SIGINT, cleanup);
+ 
+ 	while ((umad = mad_receive_via(buf, -1, srcport))) {
+ 		if (umad_status(buf)) {
+@@ -261,7 +280,25 @@
+ 	char line[1024] = { 0 }, *s, *e;
+ 	FILE *f;
+ 	int ncpu = 0;
++#if defined(__SVR4) && defined(__sun)
++	int		i;
++	char		mhz[8];
++	sol_cpu_info_t	*cpu_info;
+ 
++	ncpu = sol_get_cpu_info(&cpu_info);
++	ncpu = ncpu < MAX_CPUS ? ncpu : MAX_CPUS;
++	if (ncpu <= 0) {
++		IBWARN("couldn't get cpu info");
++		return 0;
++	}
++
++	for (i = 0; i < ncpu; i++) {
++		cpus[i].model = strdup(cpu_info[i].cpu_name);
++		snprintf(mhz, 8, "%d", cpu_info[i].cpu_mhz);
++		cpus[i].mhz = strdup(mhz);
++	}
++	free(cpu_info);
++#else
+ 	if (!(f = fopen("/proc/cpuinfo", "r"))) {
+ 		IBWARN("couldn't open /proc/cpuinfo");
+ 		return 0;
+@@ -287,6 +324,7 @@
+ 	}
+ 
+ 	fclose(f);
++#endif
+ 
+ 	DEBUG("ncpu %d", ncpu);
+ 
+@@ -314,7 +352,7 @@
+ {
+ 	int mgmt_classes[3] =
+ 	    { IB_SMI_CLASS, IB_SMI_DIRECT_CLASS, IB_SA_CLASS };
+-	int sysstat_class = IB_VENDOR_OPENIB_SYSSTAT_CLASS;
++	int sysstat_class = IB_VENDOR_OPENIB_SYSSTAT_CLASS, i;
+ 	ib_portid_t portid = { 0 };
+ 	int attr = IB_PING_ATTR;
+ 	char *err;
+@@ -342,6 +380,8 @@
+ 	if (!srcport)
+ 		IBERROR("Failed to open '%s' port '%d'", ibd_ca, ibd_ca_port);
+ 
++	bzero((void *)cpus, MAX_CPUS * sizeof (cpu_info));
++
+ 	if (server) {
+ 		if (mad_register_server_via(sysstat_class, 1, 0, oui, srcport) <
+ 		    0)
+@@ -366,5 +406,6 @@
+ 		IBERROR("ibsystat to %s: %s", portid2str(&portid), err);
+ 
+ 	mad_rpc_close_port(srcport);
++
+ 	exit(0);
+ }
 diff -r -u /tmp/infiniband-diags-1.5.8/src/ibnetdiscover.c infiniband-diags-1.5.8/src/ibnetdiscover.c
 --- /tmp/infiniband-diags-1.5.8/src/ibnetdiscover.c	Wed Feb 16 02:13:21 2011
 +++ infiniband-diags-1.5.8/src/ibnetdiscover.c	Thu Feb 24 11:27:00 2011
@@ -1630,7 +1772,19 @@ diff -r -u /tmp/infiniband-diags-1.5.8/src/ibportstate.c infiniband-diags-1.5.8/
  	int changed = 0;
  	int i;
  	long val;
-@@ -431,6 +432,12 @@
+@@ -351,6 +352,11 @@
+ 		port_op = QUERY;
+ 
+ 	is_switch = get_node_info(&portid, data);
++	if (!is_switch && (port_op == RESET || port_op == DISABLE ||
++	    port_op == ENABLE)) {
++		mad_rpc_close_port(srcport);
++		exit(-1);
++	}
+ 
+ 	if (port_op != QUERY || changed)
+ 		printf("Initial %s PortInfo:\n", is_switch ? "Switch" : "CA");
+@@ -431,6 +437,12 @@
  			mad_decode_field(data, IB_PORT_LINK_SPEED_ENABLED_F,
  					 &lse);
  
@@ -1643,7 +1797,7 @@ diff -r -u /tmp/infiniband-diags-1.5.8/src/ibportstate.c infiniband-diags-1.5.8/
  			/* Setup portid for peer port */
  			memcpy(&peerportid, &portid, sizeof(peerportid));
  			peerportid.drpath.cnt = 1;
-@@ -440,6 +447,7 @@
+@@ -440,6 +452,7 @@
  			if (ib_resolve_self_via(&selfportid,
  						&selfport, 0, srcport) < 0)
  				IBERROR("could not resolve self");
