opensmalltalk cog-spur: add test/testrunner.sh and test/result-all.master

diff --git a/components/runtime/smalltalk/cog-spur/inisqueak5c b/components/runtime/smalltalk/cog-spur/inisqueak5c
--- a/components/runtime/smalltalk/cog-spur/inisqueak5c
+++ b/components/runtime/smalltalk/cog-spur/inisqueak5c
@@ -41,10 +41,11 @@
 # subtle difference between SqueakV46.sources not SqueakV4.6.sources
 MAJOR=5.3
 MAJORV=50
-VERSION=5.3-19480
+VERSION=5.3-19481
 
 REMOTESRC="http://files.squeak.org/sources_files/"
 REMOTESOURCES=SqueakV${MAJORV}.sources.gz
+# currently only download 64bit image
 SUFFIX64="-64bit"
 REMOTEIMAGE=Squeak${VERSION}${SUFFIX64}
 REMOTEIMAGEZIP=${REMOTEIMAGE}.zip
@@ -68,6 +69,8 @@ startup=true
 batch=false
 interactive=true
 remote=true
+# in 5.3 19480 and 19481 the sources seem to be in the zip image 
+remotesrc=false
 
 while true; do
   case "$1" in
@@ -110,7 +113,7 @@ missing()
   exit 1
 }
 
-if ${remote}; then
+if ${remotesrc}; then
   echo "Downloading $REMOTESOURCES from $REMOTESRC"
   wget -O $REMOTESOURCES $REMOTESRC/$REMOTESOURCES
   case $? in
@@ -122,7 +125,18 @@ if ${remote}; then
    0) ;;
    *) echo "Unable to unzip $REMOTESOURCES"; exit 1;
   esac
+fi
+
+if ${remote}; then
   echo "Downloading $REMOTEIMAGEZIP from $REMOTEDIR"
+  if [ -f $REMOTEIMAGEZIP ]
+  then
+    rm $REMOTEIMAGEZIP Squeak${VERSION}${SUFFIX64}.image Squeak${VERSION}${SUFFIX64}.changes
+    case $? in
+      0) ;;
+      *) echo "Unable to clean up existing $REMOTEIMAGEZIP"; exit 1;
+    esac
+  fi
   wget -O $REMOTEIMAGEZIP $REMOTEDIR/$REMOTEIMAGEZIP
   case $? in
    0) ;;
