tools/perl-integrate-module: support for patches and for components without tests

diff --git a/tools/perl-integrate-module b/tools/perl-integrate-module
--- a/tools/perl-integrate-module
+++ b/tools/perl-integrate-module
@@ -116,13 +116,19 @@ if git ls-files --error-unmatch Makefile > /dev/null 2>&1 ; then
 	gmake clobber > /dev/null 2>&1
 fi
 
-# Remove everything from git (except history and perl-integrate-module.conf)
+# Remove everything from git (except known patches, history, and perl-integrate-module.conf)
+touch perl-integrate-module.conf
+grep "^%patch%" perl-integrate-module.conf | while read TAG PATCH ; do rm -f "patches/$PATCH" ; done
 rm -f history perl-integrate-module.conf
 find . -type f | while read f ; do git rm "$f" > /dev/null 2>&1 ; done
 rm -rf "$DIR"
 git checkout history > /dev/null 2>&1
 git checkout perl-integrate-module.conf > /dev/null 2>&1
 touch perl-integrate-module.conf
+grep "^%patch%" perl-integrate-module.conf | while read TAG PATCH ; do
+	git checkout "patches/$PATCH" > /dev/null 2>&1
+	[[ -f "patches/$PATCH" ]] || printf "ERROR: Patch %s not found\n" "$PATCH" >&2
+done
 
 
 # Makefile template
@@ -415,9 +421,14 @@ git add Makefile
 mkdir -p test
 touch test/results-all.master
 gmake test > /dev/null 2>&1
-find build/test -type f -name "*.snapshot" -exec cp {} test/results-all.master \;
-gmake test > /dev/null 2>&1 || printf "ERROR: 'gmake test' failed!\n" >&2
-git add test/results-all.master
+if [[ ! -d build/test ]] ; then
+	rm -rf test
+else
+	find build/test -type f -name "*.snapshot" -exec cp {} test/results-all.master \;
+	gmake test > /dev/null 2>&1 || printf "ERROR: 'gmake test' failed!\n" >&2
+	git add test/results-all.master
+	[[ -s test/results-all.master ]] || printf "WARNING: 'gmake test' produced empty results\n" >&2
+fi
 
 
 # Publish packages and create pkg5 file
