tools/perl-integrate-module: get download_url for specified version, not always the latest

diff --git a/tools/perl-integrate-module b/tools/perl-integrate-module
--- a/tools/perl-integrate-module
+++ b/tools/perl-integrate-module
@@ -94,6 +94,7 @@ if [[ -z "$VERSION" ]] ; then
 fi
 
 # Get module author
+# TODO: here we get author of the latest version, not the specified version
 AUTHOR=$(printf "%s" "$METACPAN_MODULE" | /usr/bin/jq -r '.author')
 if (($? != 0)) || [[ -z "$AUTHOR" || "$AUTHOR" == "null" ]] ; then
 	printf "FATAL: Failed to get author for module %s from metacpan\n" "$MODULE" >&2
@@ -101,9 +102,9 @@ if (($? != 0)) || [[ -z "$AUTHOR" || "$AUTHOR" == "null" ]] ; then
 fi
 
 # Get download_url
-DOWNLOAD_URL=$(printf "%s" "$METACPAN_MODULE" | /usr/bin/jq -r '.download_url')
+DOWNLOAD_URL=$($CURL "$APIURL/download_url/$MODULE?version===$VERSION" | /usr/bin/jq -r '.download_url')
 if (($? != 0)) || [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]] ; then
-	printf "WARNING: Failed to get download_url for module %s from metacpan\n" "$MODULE" >&2
+	printf "WARNING: Failed to get download_url for module %s, version %s from metacpan\n" "$MODULE" "$VERSION" >&2
 	DOWNLOAD_URL=
 fi
 
