tools/perl-integrate-module: support for per version test results

diff --git a/tools/perl-integrate-module b/tools/perl-integrate-module
--- a/tools/perl-integrate-module
+++ b/tools/perl-integrate-module
@@ -381,10 +381,6 @@ fi
 sed -i -e 's/license:TODO/'"$LICENSE"'/g' Makefile
 
 
-# Check for Makefile completeness
-grep -q "TODO" Makefile && printf "ERROR: Makefile is not complete (TODO found)\n"
-
-
 # Create manifests
 if ! gmake sample-manifest > /dev/null 2>&1 ; then
 	printf "ERROR: 'gmake sample-manifest' failed!\n" >&2
@@ -412,23 +408,44 @@ gmake REQUIRED_PACKAGES > /dev/null 2>&1 || printf "ERROR: 'gmake REQUIRED_PACKA
 git add Makefile
 
 
+# Check for Makefile completeness
+grep -q "TODO" Makefile && printf "ERROR: Makefile is not complete (TODO found)\n"
+
+
 # Make sure the build environment is setup properly and we do have all
 # requirements installed.  Otherwise we cannot continue.
 ! gmake env-check > /dev/null 2>&1 && printf "FATAL: 'gmake env-check' failed!\n" >&2 && exit 1
 
 
-# Run tests and create results-all.master file
-mkdir -p test
-touch test/results-all.master
-gmake test > /dev/null 2>&1
-if [[ ! -d build/test ]] ; then
-	rm -rf test
-else
-	find build/test -type f -name "*.snapshot" -exec cp {} test/results-all.master \;
-	gmake test > /dev/null 2>&1 || printf "ERROR: 'gmake test' failed!\n" >&2
-	git add test/results-all.master
-	[[ -s test/results-all.master ]] || printf "WARNING: 'gmake test' produced empty results\n" >&2
-fi
+PERL_VERSIONS=$(gmake print-value-PERL_VERSIONS)
+
+
+# Run tests and create results master file(s)
+COMPONENT_TEST_MASTER_PREV=
+for v in $PERL_VERSIONS ; do
+	COMPONENT_TEST_MASTER=$(gmake PERL_VERSION=$v print-value-COMPONENT_TEST_MASTER)
+	COMPONENT_TEST_SNAPSHOT=$(gmake PERL_VERSION=$v print-value-COMPONENT_TEST_SNAPSHOT)
+	mkdir -p $(dirname "$COMPONENT_TEST_MASTER")
+	touch "$COMPONENT_TEST_MASTER"
+	gmake PERL_VERSIONS=$v test > /dev/null 2>&1
+	TEST_RET=$?
+	# If there is no snapshot produced the component likely does not support tests
+	if [[ ! -f "$COMPONENT_TEST_SNAPSHOT" ]] ; then
+		printf "WARNING: test unsupported for %s\n" "$v" >&2
+		rm -f "$COMPONENT_TEST_MASTER"
+		rmdir $(dirname "$COMPONENT_TEST_MASTER")
+		continue
+	fi
+	if [[ "$COMPONENT_TEST_MASTER_PREV" != "$COMPONENT_TEST_MASTER" ]] ; then
+		[[ -s "$COMPONENT_TEST_SNAPSHOT" ]] || printf "WARNING: 'gmake test' produced empty results for %s\n" "$v" >&2
+		cp -p "$COMPONENT_TEST_SNAPSHOT" "$COMPONENT_TEST_MASTER"
+		git add "$COMPONENT_TEST_MASTER"
+		COMPONENT_TEST_MASTER_PREV="$COMPONENT_TEST_MASTER"
+		gmake PERL_VERSIONS=$v test > /dev/null 2>&1
+		TEST_RET=$?
+	fi
+	((TEST_RET != 0)) && printf "ERROR: 'gmake test' failed for %s!\n" "$v" >&2
+done
 
 
 # Publish packages and create pkg5 file
@@ -474,7 +491,6 @@ else
 	((REBUILD)) || MSG="update to $VERSION"
 
 	NV=
-	PERL_VERSIONS=$(gmake print-value-PERL_VERSIONS)
 	for v in $PERL_VERSIONS ; do
 		PLV=${v//.}
 		pkg list -avH "$COMPONENT_FMRI-$PLV" 2>/dev/null | egrep -q -v '(o|r)$' && continue
