tools/python-integrate-project: check requires_python

diff --git a/tools/python-integrate-project b/tools/python-integrate-project
--- a/tools/python-integrate-project
+++ b/tools/python-integrate-project
@@ -123,12 +123,21 @@ if [[ -z "$VERSION" || -z "$HOMEPAGE" || -z "$SUMMARY" ]] ; then
 fi
 
 
-# Find the latest version if not already provided
+# Find the latest version if not already provided and get requires_python
+REQUIRES_PYTHON=
 if [[ -z "$VERSION" ]] ; then
+	# Get version
 	VERSION=$(printf "%s" "$PYPI_PROJECT" | /usr/bin/jq -r '.info.version')
 	if (($? != 0)) || [[ -z "$VERSION" || "$VERSION" == "null" ]] ; then
 		printf "FATAL: Failed to get version for project %s from pypi\n" "$PROJECT" >&2
 		exit 1
+	fi
+
+	# Get requires_python
+	REQUIRES_PYTHON=$(printf "%s" "$PYPI_PROJECT" | /usr/bin/jq -r '.info.requires_python')
+	if (($? != 0)) || [[ -z "$REQUIRES_PYTHON" || "$REQUIRES_PYTHON" == "null" ]] ; then
+		printf 'WARNING: Failed to get requires_python from PyPI\n' >&2
+		REQUIRES_PYTHON=
 	fi
 fi
 
@@ -161,6 +170,15 @@ if git ls-files --error-unmatch Makefile > /dev/null 2>&1 ; then
 fi
 
 
+# Get release data from PyPI if needed
+if [[ -z "$DOWNLOAD_URL" || -z "$REQUIRES_PYTHON" ]] ; then
+	PYPI_PROJECT_RELEASE=$($CURL "$APIURL/$PROJECT/$VERSION/json")
+	if (($? != 0)) || [[ -z "$PYPI_PROJECT_RELEASE" ]] ; then
+		printf 'ERROR: Failed to get data for version %s from PyPI\n' "$VERSION" >&2
+		PYPI_PROJECT_RELEASE=
+	fi
+fi
+
 # Get project homepage if not already provided
 if [[ -z "$HOMEPAGE" ]] ; then
 	for field in '.info.home_page' '.info.project_urls.Homepage' '.info.project_urls.homepage' ; do
@@ -176,18 +194,20 @@ fi
 
 # Get download url if not already provided
 if [[ -z "$DOWNLOAD_URL" ]] ; then
-	# Get release data from pypi
-	PYPI_PROJECT_RELEASE=$($CURL "$APIURL/$PROJECT/$VERSION/json")
-	if (($? != 0)) || [[ -z "$PYPI_PROJECT_RELEASE" ]] ; then
-		printf "FATAL: Failed to get data for version %s from pypi\n" "$VERSION" >&2
-		exit 1
-	fi
-
-	# Get download url
 	DOWNLOAD_URL=$(printf "%s" "$PYPI_PROJECT_RELEASE" | /usr/bin/jq -r '.urls[]|select(.packagetype=="sdist")|.url')
 	if (($? != 0)) || [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]] ; then
 		printf "WARNING: Failed to get download url for project %s, version %s from pypi\n" "$PROJECT" "$VERSION" >&2
 		DOWNLOAD_URL=
+	fi
+fi
+
+# Get requires_python if not yet known
+if [[ -z "$REQUIRES_PYTHON" ]] ; then
+	# Get requires_python
+	REQUIRES_PYTHON=$(printf "%s" "$PYPI_PROJECT_RELEASE" | /usr/bin/jq -r '.info.requires_python')
+	if (($? != 0)) || [[ -z "$REQUIRES_PYTHON" || "$REQUIRES_PYTHON" == "null" ]] ; then
+		printf 'ERROR: Failed to get requires_python for version %s from PyPI\n' "$VERSION" >&2
+		REQUIRES_PYTHON=
 	fi
 fi
 
@@ -410,7 +430,17 @@ fi
 sed -i -e 's/license:TODO/'"$LICENSE"'/g' Makefile
 
 
+# Make sure our Python versions are supported
 PYTHON_VERSIONS=$($GMAKE print-value-PYTHON_VERSIONS)
+for v in $PYTHON_VERSIONS ; do
+	if ! python$v -c 'import packaging' > /dev/null 2>&1 ; then
+		printf 'WARNING: Missing packaging for Python %s (bootstrap?)\n' "$v" >&2
+		continue
+	fi
+	if ! python$v -c "import sys; from packaging.specifiers import SpecifierSet; sys.exit(0 if '$v' in SpecifierSet('$REQUIRES_PYTHON') else 1)" ; then
+		printf 'ERROR: version %s does not support Python %s\n' "$VERSION" "$v" >&2
+	fi
+done
 
 
 # detect TEST_STYLE
